package victronDevice

import (
	vd "github.com/koestler/go-victron/victronDefinitions"
)

func RegisterFactoryByProduct(product vd.VeProduct) []VictronRegister {
	switch product {
	case vd.VeProductBMV700:
		return RegisterListBmv700
	case vd.VeProductBMV702:
		return RegisterListBmv702
	case vd.VeProductBMV700H:
		return RegisterListBmv700
	case vd.VeProductBlueSolarMPPT70_15:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT75_50:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_35:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT75_15:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_15:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_30:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_50:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_70:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_100:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_50rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_30rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_35rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT75_10:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_45:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_60:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_85:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_100:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_100:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_85:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT75_15:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT75_10:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT100_15:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT100_30:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT100_50:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_35:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_100rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_85rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_70:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_85:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_60:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_45:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT100_20:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT100_2048V:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_45:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_60:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_70:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_85rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_100rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_20:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_2048V:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_60rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT250_70rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_45rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_60rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_70rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_85rev3:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT150_100rev3:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_45rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_60rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_70rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_45rev3:
		return RegisterListSolar
	case vd.VeProductSmatrtSolarMPPT150_45rev3:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT70_10rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPT75_15rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_30rev3:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_50rev3:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT150_35rev3:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT75_10rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT75_15rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPT100_15rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_70:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_45:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_60:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_85:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_100:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_45:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_60:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_70:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_85:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_100:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_70rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_85rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan150_100rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPTVECan150_100:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPTVECan250_70:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPTVECan250_100:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_70rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_100rev2:
		return RegisterListSolar
	case vd.VeProductSmartSolarMPPTVECan250_85rev2:
		return RegisterListSolar
	case vd.VeProductBlueSolarMPPTVECan150_100rev2:
		return RegisterListSolar
	case vd.VeProductPhoenixInverter12V250VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V250VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V250VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V250VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V250VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V250VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V375VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V375VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V375VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V375VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V375VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V375VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V500VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V500VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V500VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V500VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V500VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V500VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V800VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V800VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V800VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V800VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V800VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V800VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V1200VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V1200VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V1200VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V1200VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V1200VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V1200VA120V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V1600VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V1600VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V1600VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V2000VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V2000VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V2000VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V3000VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V3000VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V3000VA230V:
		return RegisterListInverter
	case vd.VeProductPhoenixInverterSmart12V5000VA230Vac64k:
		return RegisterListInverter
	case vd.VeProductPhoenixInverterSmart24V5000VA230Vac64k:
		return RegisterListInverter
	case vd.VeProductPhoenixInverterSmart48V5000VA230Vac64k:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V800VA230Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V800VA230Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V800VA230Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V800VA120Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V800VA120Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V800VA120Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V1200VA230Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V1200VA230Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V1200VA230Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter12V1200VA120Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter24V1200VA120Vac64kHS:
		return RegisterListInverter
	case vd.VeProductPhoenixInverter48V1200VA120Vac64kHS:
		return RegisterListInverter
	case vd.VeProductBMV712Smart:
		return RegisterListBmv712
	case vd.VeProductBMV710HSmart:
		return RegisterListBmv712
	case vd.VeProductBMV712SmartRev2:
		return RegisterListBmv712
	case vd.VeProductSmartShunt500A_50mV:
		return RegisterListBmv712
	case vd.VeProductSmartShunt1000A_50mV:
		return RegisterListBmv712
	case vd.VeProductSmartShunt2000A_50mV:
		return RegisterListBmv712
	}
	return nil
}
