name: Audit & Test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: |
          go install go.uber.org/mock/mockgen@latest

      - name: Generate mocks
        run: go generate -v ./...

      - name: Test
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62